### ISSUE TITLE
Speculor theme help

### ISSUE THREAD

**Issue by pingpongpedro** [Prelc/Speculor-WP#4]
Hi

I am trying to add the sub menu with the email, phone and social media details.
And also the text where it says ‘refine your business’.

Can you help please.

Ta
Pete

**Comment by Prelc** [comment]
Hi Pete,

Sorry, for a really late answer. You can add the email, phone and social media details in the wp-admin -> Appearance -> Widgets -> Header left or Header right. Here you can add text widgets with all the content.

You can change "Refine your business" text in the wp-admin -> Customizer -> Header Image.

Take care!
